# Generated by Django 5.2.17 on 2026-09-27 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(help_text='Ex.: Bloco B, próximo à cantina.', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('codigo', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Código único usado no QR Code.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Pontos ganhos por unidade reciclada deste resíduo.')),
                ('icone', models.CharField(blank=True, help_text='Emoji ou símbolo curto (ex.: ♻️).', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resíduo',
                'verbose_name_plural': 'Resíduos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroReciclagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Pontos calculados no momento do registro (snapshot).')),
                ('confirmado', models.BooleanField(default=True, help_text='Auditoria: admin pode invalidar um registro depois.')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ponto_coleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='coleta.pontocoleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_reciclagem', to=settings.AUTH_USER_MODEL)),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='coleta.residuo')),
            ],
            options={
                'verbose_name': 'Registro de Reciclagem',
                'verbose_name_plural': 'Registros de Reciclagem',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['usuario', '-data'], name='coleta_regi_usuario_39689e_idx')],
            },
        ),
    ]
